version: '2'
services:
  confluent-schema-registry:
    image: 'confluentinc/cp-schema-registry:3.2.1'
    network_mode: host
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      SCHEMA_REGISTRY_HOST_NAME: 107.21.166.171
    restart: always
  confluent-rest-proxy:
    image: 'confluentinc/cp-kafka-rest:3.2.1'
    network_mode: host
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka1:9092,kafka2:9092,kafka3:9092'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082/'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://localhost:8081/'
      KAFKA_REST_HOST_NAME: 107.21.166.171
    depends_on:
      - confluent-schema-registry
    restart: always
  kafka-topics-ui:
    image: 'landoop/kafka-topics-ui:0.9.2'
    network_mode: host
    environment:
      KAFKA_REST_PROXY_URL: 'http://localhost:8082'
      PROXY: 'TRUE'
    depends_on:
      - confluent-rest-proxy
    restart: always

